### PR TITLE
Last RC

### PR DESCRIPTION
**Pull request by Daniele-rolli**
## Pull Request Type
- [x] **Feature/Component** (New feature or component)
- [ ] **Bug Fix** (Fixes an issue or bug)
- [ ] **Minor Change** (Documentation, README updates, or small UI tweaks)

### 1. General
- [ ] Does this PR address the **intended feature/bug** without any unintended changes?
- [ ] Have **all new changes been tested** on both Android and iOS?
- [ ] Is the **UI/UX** consistent across different devices and screen sizes (Phones/Tablets)?

### 2. Permissions & Security
- [x] Does this PR request **new permissions** (e.g., location, camera, storage)? If yes, specify details:
- [x] Have the implications of these permissions been **documented** and **justified**?

### 3. Platform-Specific Code
- [x] Have you made any modifications to **Xcode** or **Android project files** (e.g., Gradle, Info.plist)?
- [x] Have these changes been tested thoroughly on **simulators/emulators** and **real devices**?
      
### 4. Store Compliance
- [x] Does this PR comply with **Google Play Store** guidelines (permissions, content policies)?
- [x] Does this PR comply with **Apple App Store** guidelines (privacy, security, UI design)?

### 5. Translations & Cross-Platform
- [ ] Have **translations** been updated for all new user-facing components?
- [ ] Have you confirmed that the **same work will be applied to the desktop app** (if applicable)?

## Minor Changes (Documentation, Small UI Tweaks)
- [ ] Does this PR include only **non-functional changes** (e.g., documentation, small UI tweaks)?
- [ ] Are these changes **safe** and do not affect core app functionality?

Beaver Pocket is almost ready for its final release candidate. The only remaining issues are the drawing component, which needs improvement and porting to Beaver Notes, and localization. We should also start addressing some issues in Beaver Notes, as they have been piling up.

### CODE REVIEW

**Comment by bigshans** [comment]
Hi @Daniele-rolli , how do I build this code to android apk?

**Comment by Daniele-rolli** [comment]
You need Ionic to build and open Android Studio. Run `yarn exec yarn run ionic:build && yarn exec cap copy`, and then `yarn exec cap open android` to open Android Studio. In Android Studio, you can run the app by either connecting a device via USB and using the debugger, or by going to **Build > Build Bundle(s) / APK(s) > Build APK(s)**. Feel free to ask if you need something else.

**Comment by bigshans** [comment]
Yes, but I meet another problem. It looks like the environment variable missing.

图片

**Comment by Daniele-rolli** [comment]
The app requires two environment variables to communicate with Google Drive and OneDrive. To set this up, create a file called `gradle.properties` in the `Beaver-pocket/android/app` directory, and add the following:

```gradle
GOOGLE_CLIENT_ID=<Your_Google_Client_ID>
ONEDRIVE_SHA1=/<Your_OneDrive_SHA1>
```

I don't think it will give you trouble if you leave the placeholders there

**Comment by bigshans** [comment]
Great! Thanks, I build it successfully.

**Comment by bigshans** [comment]
1. Nothing happened when clicking the record button. It seems to be a permission issue. It is best to apply for permission here.
2. Search highlighting is abnormal.
3. Click the edge of the navigation bar button, and the button may light up but not switch routes. The location is not very good to touch, and you need to try several times.
4. After entering the secondary page (shortcut page, about page, etc.) of settings and returning, you will not return to the settings page, but to the home page.
5. The collapsible heading behaves abnormally when the Enter key is pressed. If the Enter key is pressed in the middle, the following text will be lost. When the Enter key is pressed at the end of the title, there will be no line break.
6. When clicking the search button while the input method is raised, the search box is in the wrong position.

> [!TIP]
> About the second point:
> 1. Enter the note, click the search button, enter the keyword in the search box, and search. After the highlight appears, re-enter the note and search for the keyword again. The keyword will not be highlighted.
> 2. It is worth mentioning that after re-entering the note if you make any changes to the note, the highlight will reappear, even if you are not in the search state now. The highlight cannot be cleared, and you will only highlight a different word when you search again.

**Comment by Daniele-rolli** [comment]
Thanks for looking into it.

1. Fixed - Permissions issue
2. Looking into it
3. Needs clarification on which component
4. Looking into it
5. Looking into it – I honestly have no clue, as this is a direct port of Beaver Notes' collapsible headings
6. Cannot replicate in the Android emulator or Xcode simulator

While I investigate these, could you help me with the headings (plain JavaScript) and the drawing component, which still has some issues? I've attached a video to give you a better understanding.


https://github.com/user-attachments/assets/88990923-d5ce-4fda-a400-e6db6e29e6e1

**Comment by bigshans** [comment]
I debugged the collapsible title. It works fine on the web, including on the mobile browser, but it is abnormal in ionic. It seems like an ionic problem.

**Comment by Daniele-rolli** [comment]
It might be something related to storage, as both the web and mobile versions use Ionic; the only difference I can think of is the storage plugin.

**Comment by Daniele-rolli** [comment]
@bigshans, have you discovered anything new? I’ve even checked in Xcode’s logs, but everything seems to work fine. However, the headings still aren't behaving as expected.

```
⚡️  To Native ->  Filesystem getUri 80882052
⚡️  TO JS {"uri":"file:\/\/\/Users\/danielerolli\/Library\/Developer\/CoreSimulator\/Devices\/44E8D25A-2FBD-4D0C-9241-B7A30791E07E\/data\/Containers\/Data\/Application\/6783F24E-C360-43C7-A97C-76F2F473A2EF\/Documents\/"}
⚡️  To Native ->  Filesystem mkdir 80882053
⚡️  TO JS undefined
⚡️  To Native ->  Filesystem mkdir 80882054
⚡️  TO JS undefined
⚡️  To Native ->  Filesystem mkdir 80882055
⚡️  TO JS undefined
⚡️  To Native ->  Filesystem mkdir 80882056
⚡️  TO JS undefined
⚡️  To Native ->  Filesystem stat 80882057
⚡️  TO JS {"ctime":1726512231210,"mtime":1731234900302,"uri":"file:\/\/\/Users\/danielerolli\/Library\/Developer\/CoreSimulator\/Devices\/44E8D25A-2FBD-4D0C-9241-B7A30791E07E\/data\/Containers\/Data\/Application\/6783F24E-C360-43C7-A97C-76F2F473A2EF\/Documents\/note
⚡️  To Native ->  Filesystem readFile 80882058
⚡️  TO JS {"data":"{\"data\":{\"notes\":{\"f31d4b77-c9af-432a-a787-5fe5a3ff1212\":{\"id\":\"f31d4b77-c9af-432a-a787-5fe5a3ff1212\",\"title\":\"New Note\",\"content\":{\"type\":\"doc\",\"content\":[]},\"createdAt\":1726512231202,\"updatedAt\":1726512231202,\"labels\"
⚡️  To Native ->  Filesystem writeFile 80882059
⚡️  TO JS {"uri":"file:\/\/\/Users\/danielerolli\/Library\/Developer\/CoreSimulator\/Devices\/44E8D25A-2FBD-4D0C-9241-B7A30791E07E\/data\/Containers\/Data\/Application\/6783F24E-C360-43C7-A97C-76F2F473A2EF\/Documents\/notes\/data.json"}
⚡️  To Native ->  App addListener 80882060
⚡️  To Native ->  Keyboard setResizeMode 80882061
⚡️  TO JS undefined
⚡️  To Native ->  Filesystem getUri 80882062
⚡️  TO JS {"uri":"file:\/\/\/Users\/danielerolli\/Library\/Developer\/CoreSimulator\/Devices\/44E8D25A-2FBD-4D0C-9241-B7A30791E07E\/data\/Containers\/Data\/Application\/6783F24E-C360-43C7-A97C-76F2F473A2EF\/Documents\/"}
⚡️  To Native ->  Filesystem mkdir 80882063
⚡️  TO JS undefined
⚡️  To Native ->  Filesystem mkdir 80882064
⚡️  TO JS undefined
⚡️  To Native ->  Filesystem mkdir 80882065
⚡️  TO JS undefined
⚡️  To Native ->  Filesystem mkdir 80882066
⚡️  TO JS undefined
⚡️  To Native ->  Filesystem stat 80882067
⚡️  TO JS {"ctime":1726512231210,"type":"file","uri":"file:\/\/\/Users\/danielerolli\/Library\/Developer\/CoreSimulator\/Devices\/44E8D25A-2FBD-4D0C-9241-B7A30791E07E\/data\/Containers\/Data\/Application\/6783F24E-C360-43C7-A97C-76F2F473A2EF\/Documents\/notes\/data.
⚡️  To Native ->  Filesystem readFile 80882068
⚡️  TO JS {"data":"{\"data\":{\"notes\":{\"f31d4b77-c9af-432a-a787-5fe5a3ff1212\":{\"id\":\"f31d4b77-c9af-432a-a787-5fe5a3ff1212\",\"title\":\"New Note\",\"content\":{\"type\":\"doc\",\"content\":[]},\"createdAt\":1726512231202,\"updatedAt\":1726512231202,\"labels\"
⚡️  To Native ->  Filesystem writeFile 80882069
⚡️  TO JS {"uri":"file:\/\/\/Users\/danielerolli\/Library\/Developer\/CoreSimulator\/Devices\/44E8D25A-2FBD-4D0C-9241-B7A30791E07E\/data\/Containers\/Data\/Application\/6783F24E-C360-43C7-A97C-76F2F473A2EF\/Documents\/notes\/data.json"}
⚡️  To Native ->  App addListener 80882070
⚡️  To Native ->  Keyboard setResizeMode 80882071
⚡️  TO JS undefined
```

**Comment by bigshans** [comment]
Nothing new was found.

**Comment by Daniele-rolli** [comment]
Since we can’t seem to solve this, we could remove the component and focus on something more important, like the drawing component. I’ve sent you the video so you can see what’s wrong with the component if we take this approach.

**Comment by bigshans** [comment]
Hi @Daniele-rolli , here are two unused variables that you need to fix.

图片

**Comment by bigshans** [comment]
Is the drawing hidden?

**Comment by Daniele-rolli** [comment]
I've fixed the variable issues and made the drawing component available on phones as well. It's primarily designed for tablets and uses pointer gestures, so only a pen can be used for drawing.

**Comment by bigshans** [comment]
The paper component is unavailable on my phone. I can't draw on it by touch on my phone.

**Comment by Daniele-rolli** [comment]
Yeah, about that—as I might have mentioned before—to prevent users from drawing accidentally, I limited the drawing component to respond only to tools like the Apple Pencil or S Pen. Scrolling is handled with two fingers, though it's not perfect. If you'd like to add touch support for finger drawing, you can modify **line 67 in `DrawMode.jsx`** by adding `event.pointerType === "touch"` alongside `"pen"` to enable drawing with fingers.

Here’s the updated code snippet:

```javascript
    const handlePointerEvent = (event) => {
      event.preventDefault();
      event.stopPropagation();

      if (event.pointerType === "pen" || event.pointerType === "touch") { // Add "touch" here
        if (event.touches && event.touches.length > 1) {
          setDrawing(false);
          return;
        }

        const [x, y] = getPointerCoordinates(event);

        if (event.type === "pointerdown") {
          if (tool === "erase") {
            isErasing = true;
            eraseOverlappingPaths(x, y); // Start erasing immediately
          } else {
            startDrawing(x, y);
          }
        } else if (event.type === "pointermove") {
          if (tool === "erase" && isErasing) {
            eraseOverlappingPaths(x, y); // Continuously erase during movement
          } else if (tool !== "erase") {
            draw(x, y);
          }
        } else if (event.type === "pointerup") {
          if (tool === "erase") {
            isErasing = false; // Stop erasing after pointer is lifted
          } else {
            stopDrawing();
          }
        }
      }
    };
```

**Comment by bigshans** [comment]
> Yeah, about that—as I might have mentioned before—to prevent users from drawing accidentally, I limited the drawing component to respond only to tools like the Apple Pencil or S Pen. Scrolling is handled with two fingers, though it's not perfect. If you'd like to add touch support for finger drawing, you can modify **line 67 in `DrawMode.jsx`** by adding `event.pointerType === "touch"` alongside `"pen"` to enable drawing with fingers.
> 
> Here’s the updated code snippet:
> 
> ```js
>     const handlePointerEvent = (event) => {
>       event.preventDefault();
>       event.stopPropagation();
> 
>       if (event.pointerType === "pen" || event.pointerType === "touch") { // Add "touch" here
>         if (event.touches && event.touches.length > 1) {
>           setDrawing(false);
>           return;
>         }
> 
>         const [x, y] = getPointerCoordinates(event);
> 
>         if (event.type === "pointerdown") {
>           if (tool === "erase") {
>             isErasing = true;
>             eraseOverlappingPaths(x, y); // Start erasing immediately
>           } else {
>             startDrawing(x, y);
>           }
>         } else if (event.type === "pointermove") {
>           if (tool === "erase" && isErasing) {
>             eraseOverlappingPaths(x, y); // Continuously erase during movement
>           } else if (tool !== "erase") {
>             draw(x, y);
>           }
>         } else if (event.type === "pointerup") {
>           if (tool === "erase") {
>             isErasing = false; // Stop erasing after pointer is lifted
>           } else {
>             stopDrawing();
>           }
>         }
>       }
>     };
> ```

It works. But except for the interface display problem, there are no problems with the functionality, and the menu does not pop up as shown in the video.

**Comment by Daniele-rolli** [comment]
The component is designed more for tablets than for phones, which is why it wasn’t available initially. However, the issue is that it sometimes scrolls instead of drawing, which might be specifically related to Apple devices.

**Comment by Daniele-rolli** [comment]
Would you mind clarifying point 3? I was also thinking that we could deprecate the old drawing component, keeping it only as a preview since it has been part of Beaver Notes for at least two releases, and replace it with something improved, like a custom implementation of [tldraw](https://tldraw.dev/).

**Comment by Daniele-rolli** [comment]
I'll work on removing the collapsible headings. In the meantime, would you mind clarifying point 3?

**Comment by Daniele-rolli** [comment]
I've noticed something interesting with the collapsible headings. We already know that pressing Enter breakes the title instead of splitting it. However, the weirder behavior happens when trying to write in the now-broken "split" heading. On iOS, it starts with a capital letter, which means it recognizes it as a separate text field from the remaining part of the broken "split" title.

https://github.com/user-attachments/assets/b4a9fa30-3afc-4811-8892-afd62aa275bd

**Comment by bigshans** [comment]
I'm sorry to reply very late. My phone met some problems and recently I'm recovering it.

About the third point, when you click the edge of the tab navigation bar item, the navigation bar will be highlighted, but the corresponding page will not jump. This location is probably the blank black background above the navigation bar icons. My phone is recovering, so I can't show you right now.

About the heading, I found it when debugging before, so I guess it may be related to the keyboard. Ionic delegates many operations, breaking the pure web runtime. It would be best to prove that it has no problem under the pure web runtime.

**Comment by Daniele-rolli** [comment]
I'm sorry to hear that. Take your time to fix your phone; it sounds like a more pressing issue. While you work on that, I'll focus on resolving other issues. Once you're able to look into the headings, I’ll continue working on it as well.

**Comment by Daniele-rolli** [comment]
I've removed the collapsible headings and addressed the relevant issues. I'll work on fixing point 4 and resolving the sync issue. Once that's done, we should be ready for the final release candidate.

I'll also start adding features from Beaver Notes 3.8.0 to Pocket, which will be released as a stable version as soon as possible.

**Comment by Daniele-rolli** [comment]
> Thanks for looking into it.
> 
> 1. ~Permissions issue~. Fixed.
> 2. ~Looking into it. Solved working on 6 before pushing~.Fixed.
> 3. ~Needs clarification on which component~. Fixed
> 4. ~Looking into it~.Fixed
> 5. ~Looking into it – I honestly have no clue, as this is a direct port of Beaver Notes' collapsible headings~. Removed
> 6. ~Cannot replicate in the Android emulator or Xcode simulator. Found the issue~. Fixed.
> 
> While I investigate these, could you help me with the headings (plain JavaScript) and the drawing component, which still has some issues? I've attached a video to give you a better understanding.
> 
>  ScreenRecording_11-07-2024.22-20-04_1.MP4

Everything has been addressed. I've hidden the drawing component on mobile since it doesn’t make sense to have it on phones, it only works with a stylus, and virtually no phone has one. We can still add it when we reach the stable release in the next version. I'll wait for your approval before merging and releasing the final RC.

**Comment by bigshans** [comment]
Search still has some problems, and the page will automatically scroll up, which is annoying.

Peek 2024-11-17 20-44

**Comment by Daniele-rolli** [comment]
I've addressed the search and navbar issues. I couldn't replicate the page behavior on iOS or in the Android Studio simulator. Let me know if you find anything else.

**Pull request merged**
